### PR TITLE
add optional links; manifests/bosh-lite now promote links/cloud-config

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by drnic** [comment]
Think I still have some work to do to support `etcd.cluster` via links.

And locally having inter-node connectivity issues; not resolved yet.

**Comment by drnic** [comment]
And this issue:

```
$ curl https://etcd-0.etcd.service.cf.internal:4001/v2/keys -k
curl: (35) error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate
```

**Comment by genevievelesperance** [comment]
Hey @drnic. We are working on bosh 2.0 manifests now. Are you planning on working more on the issues you listed above in this PR or should we merge this and make those fixes?

**Comment by genevievelesperance** [comment]
@drnic We will merge this and resolve any issues as they come up.

**Comment by drnic** [comment]
My networking issues were local and fixed.
The only changes I've made since this PR were to expose properties via provides. Then I wanted to the remove to the etcd. namespace prefix but you can make the timing call on when to roll that out.
Thanks if this PR is helpful.

**Pull request merged**
