### PR TITLE
copy/paste instructions for warden

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Hi @drnic 

It's hard to tell what content changes you've made due to all the whitespace changes.  What does it have to do with warden?  Also, have you taken a look at the README preview with these new whitespace changes?  I suspect the new look is unintentional:

screen shot 2015-10-27 at 3 26 06 pm

**Comment by drnic** [comment]
Sorry will fix.

**Comment by drnic** [comment]
@Amit-PivotalLabs fixed the PR; sorry about that.

**Comment by Amit-PivotalLabs** [comment]
Thanks, I've prioritized this PR and added the following:

* README should mention the required property-overrides stub in the “Generating deployment manifest” section
* README should mention that we provide a default property-overrides stub for BOSH-Lite purposes (as we do for the other required stubs)
* `generate_etcd_deployment_manifest` provides an example in the Usage where the property-overrides and iaas-settings are out of order; both orders are effectively equivalent, but is confusing, and the order in the example should be fixed: https://github.com/cloudfoundry-incubator/etcd-release/blob/master/scripts/generate_etcd_deployment_manifest#L20-L21

**Comment by Amit-PivotalLabs** [comment]
@drnic to clarify, you don't need to make any more changes, our team will merge your PR and address the additional points I raised, which are omissions in the existing documentation, not a problem with your PR.

**Comment by medvedzver** [comment]
Merged, and added changes per amit's commits.

Mikhail & @robdimsdale

**Comment by drnic** [comment]
Thanks guys

**Comment by Amit-PivotalLabs** [comment]
This was merged separately, closing PR.

**Pull request closed without merging**
